### PR TITLE
Calls backend and renders information

### PR DESCRIPTION
**Pull request by caroljli**
* Successfully mapped interface to render information
* Need to fix information calling bug as a result of asynchronous functions and calling from the search page

**Screenshots:**
image

### CODE REVIEW

**Review by glstewart17 — COMMENTED** [review]
Looks good to me!

**Comment by glstewart17** [comment]
I changed reviewCount to checkInCount!

**Review by glstewart17 — APPROVED** [review]

**Review by Raulp8 — APPROVED** [review]
looks good!

**Comment by caroljli** [comment]
@glstewart17 thanks for letting me know! I'll update it in the interface too so things work properly haha

**Pull request merged**
