### PR TITLE
Added mobile redirect

### PR DESCRIPTION
**Pull request by caroljli**
image
* Redirects when window is size 699 px or below -- sourced from StackOverflow

### CODE REVIEW

**Comment by glstewart17** [comment]
Would this ever be thrown if someone is using a browser that only takes up a fraction of their screen?

**Review by Raulp8 — APPROVED** [review]
LGTM, also i forgot to mention this when you first implemented sorting, but should we remove the sorting by score in the backend if we have sorting here? I think its also just nice to have the stores being sorted by default but it might save us some time when sending the response.

**Comment by caroljli** [comment]
> LGTM, also i forgot to mention this when you first implemented sorting, but should we remove the sorting by score in the backend if we have sorting here? I think its also just nice to have the stores being sorted by default but it might save us some time when sending the response.

I think that's a good idea, since the default will sort it to ShopSafe Score anyway @Raulp8

**Comment by caroljli** [comment]
> Would this ever be thrown if someone is using a browser that only takes up a fraction of their screen?

It will, I'm going to look into a better fix for mobile detection. @glstewart17 

**UPDATE:** i fixed it so that it only works when the device is mobile, going to update on new PR @glstewart17

**Pull request closed without merging**
